// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.7.1
// source: ecu.proto

// package is necessary to tell grpc to generate a service name with package
// name.

package ecu

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// HAState reported by Seesaw. It's the protobuffer equivalent of Seesaw.HAState.
type SeesawStats_HAState int32

const (
	SeesawStats_HA_UNKNOWN  SeesawStats_HAState = 0
	SeesawStats_HA_BACKUP   SeesawStats_HAState = 1
	SeesawStats_HA_DISABLED SeesawStats_HAState = 2
	SeesawStats_HA_ERROR    SeesawStats_HAState = 3
	SeesawStats_HA_MASTER   SeesawStats_HAState = 4
	SeesawStats_HA_SHUTDOWN SeesawStats_HAState = 5
)

// Enum value maps for SeesawStats_HAState.
var (
	SeesawStats_HAState_name = map[int32]string{
		0: "HA_UNKNOWN",
		1: "HA_BACKUP",
		2: "HA_DISABLED",
		3: "HA_ERROR",
		4: "HA_MASTER",
		5: "HA_SHUTDOWN",
	}
	SeesawStats_HAState_value = map[string]int32{
		"HA_UNKNOWN":  0,
		"HA_BACKUP":   1,
		"HA_DISABLED": 2,
		"HA_ERROR":    3,
		"HA_MASTER":   4,
		"HA_SHUTDOWN": 5,
	}
)

func (x SeesawStats_HAState) Enum() *SeesawStats_HAState {
	p := new(SeesawStats_HAState)
	*p = x
	return p
}

func (x SeesawStats_HAState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeesawStats_HAState) Descriptor() protoreflect.EnumDescriptor {
	return file_ecu_proto_enumTypes[0].Descriptor()
}

func (SeesawStats_HAState) Type() protoreflect.EnumType {
	return &file_ecu_proto_enumTypes[0]
}

func (x SeesawStats_HAState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeesawStats_HAState.Descriptor instead.
func (SeesawStats_HAState) EnumDescriptor() ([]byte, []int) {
	return file_ecu_proto_rawDescGZIP(), []int{3, 0}
}

// Request for failover.
type FailoverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FailoverRequest) Reset() {
	*x = FailoverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ecu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailoverRequest) ProtoMessage() {}

func (x *FailoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailoverRequest.ProtoReflect.Descriptor instead.
func (*FailoverRequest) Descriptor() ([]byte, []int) {
	return file_ecu_proto_rawDescGZIP(), []int{0}
}

// Response for failover.
type FailoverResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FailoverResponse) Reset() {
	*x = FailoverResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ecu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailoverResponse) ProtoMessage() {}

func (x *FailoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailoverResponse.ProtoReflect.Descriptor instead.
func (*FailoverResponse) Descriptor() ([]byte, []int) {
	return file_ecu_proto_rawDescGZIP(), []int{1}
}

type GetStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ecu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_ecu_proto_rawDescGZIP(), []int{2}
}

// SeesawStats includes stats that are interested by syllogi.
type SeesawStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Hostname of the instance.
	Hostname string              `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	HaState  SeesawStats_HAState `protobuf:"varint,2,opt,name=ha_state,json=haState,proto3,enum=ecu.SeesawStats_HAState" json:"ha_state,omitempty"`
	// If current instance is ready to serve traffic.
	Readiness      *Readiness `protobuf:"bytes,3,opt,name=readiness,proto3" json:"readiness,omitempty"`
	FluentBitError string     `protobuf:"bytes,4,opt,name=fluent_bit_error,json=fluentBitError,proto3" json:"fluent_bit_error,omitempty"`
}

func (x *SeesawStats) Reset() {
	*x = SeesawStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ecu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeesawStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeesawStats) ProtoMessage() {}

func (x *SeesawStats) ProtoReflect() protoreflect.Message {
	mi := &file_ecu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeesawStats.ProtoReflect.Descriptor instead.
func (*SeesawStats) Descriptor() ([]byte, []int) {
	return file_ecu_proto_rawDescGZIP(), []int{3}
}

func (x *SeesawStats) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SeesawStats) GetHaState() SeesawStats_HAState {
	if x != nil {
		return x.HaState
	}
	return SeesawStats_HA_UNKNOWN
}

func (x *SeesawStats) GetReadiness() *Readiness {
	if x != nil {
		return x.Readiness
	}
	return nil
}

func (x *SeesawStats) GetFluentBitError() string {
	if x != nil {
		return x.FluentBitError
	}
	return ""
}

type Readiness struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsReady bool `protobuf:"varint,1,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	// A string message decribing why it's not ready.
	// Not filled if ready.
	// For logging and debugging purpose.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Readiness) Reset() {
	*x = Readiness{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ecu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Readiness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Readiness) ProtoMessage() {}

func (x *Readiness) ProtoReflect() protoreflect.Message {
	mi := &file_ecu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Readiness.ProtoReflect.Descriptor instead.
func (*Readiness) Descriptor() ([]byte, []int) {
	return file_ecu_proto_rawDescGZIP(), []int{4}
}

func (x *Readiness) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *Readiness) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// UpdateFluentBitRequest holds raw file contents of configs related to fluent-bit.
type UpdateFluentBitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FluentBitCfg string `protobuf:"bytes,1,opt,name=fluent_bit_cfg,json=fluentBitCfg,proto3" json:"fluent_bit_cfg,omitempty"`
	SaKey        string `protobuf:"bytes,2,opt,name=sa_key,json=saKey,proto3" json:"sa_key,omitempty"`
	ProxyEnv     string `protobuf:"bytes,3,opt,name=proxy_env,json=proxyEnv,proto3" json:"proxy_env,omitempty"`
}

func (x *UpdateFluentBitRequest) Reset() {
	*x = UpdateFluentBitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ecu_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFluentBitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFluentBitRequest) ProtoMessage() {}

func (x *UpdateFluentBitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ecu_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFluentBitRequest.ProtoReflect.Descriptor instead.
func (*UpdateFluentBitRequest) Descriptor() ([]byte, []int) {
	return file_ecu_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFluentBitRequest) GetFluentBitCfg() string {
	if x != nil {
		return x.FluentBitCfg
	}
	return ""
}

func (x *UpdateFluentBitRequest) GetSaKey() string {
	if x != nil {
		return x.SaKey
	}
	return ""
}

func (x *UpdateFluentBitRequest) GetProxyEnv() string {
	if x != nil {
		return x.ProxyEnv
	}
	return ""
}

type UpdateFluentBitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateFluentBitResponse) Reset() {
	*x = UpdateFluentBitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ecu_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFluentBitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFluentBitResponse) ProtoMessage() {}

func (x *UpdateFluentBitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ecu_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFluentBitResponse.ProtoReflect.Descriptor instead.
func (*UpdateFluentBitResponse) Descriptor() ([]byte, []int) {
	return file_ecu_proto_rawDescGZIP(), []int{6}
}

var File_ecu_proto protoreflect.FileDescriptor

var file_ecu_proto_rawDesc = []byte{
	0x0a, 0x09, 0x65, 0x63, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x65, 0x63, 0x75,
	0x22, 0x11, 0x0a, 0x0f, 0x46, 0x61, 0x69, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x46, 0x61, 0x69, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x9f, 0x02, 0x0a, 0x0b, 0x53,
	0x65, 0x65, 0x73, 0x61, 0x77, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x68, 0x61, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x65, 0x63, 0x75, 0x2e, 0x53,
	0x65, 0x65, 0x73, 0x61, 0x77, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x48, 0x41, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x07, 0x68, 0x61, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x72,
	0x65, 0x61, 0x64, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x65, 0x63, 0x75, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x09,
	0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x66, 0x6c, 0x75,
	0x65, 0x6e, 0x74, 0x5f, 0x62, 0x69, 0x74, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x42, 0x69, 0x74, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x67, 0x0a, 0x07, 0x48, 0x41, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0e,
	0x0a, 0x0a, 0x48, 0x41, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x48, 0x41, 0x5f, 0x42, 0x41, 0x43, 0x4b, 0x55, 0x50, 0x10, 0x01, 0x12, 0x0f, 0x0a,
	0x0b, 0x48, 0x41, 0x5f, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0c,
	0x0a, 0x08, 0x48, 0x41, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09,
	0x48, 0x41, 0x5f, 0x4d, 0x41, 0x53, 0x54, 0x45, 0x52, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x48,
	0x41, 0x5f, 0x53, 0x48, 0x55, 0x54, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x05, 0x22, 0x3e, 0x0a, 0x09,
	0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f,
	0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x52,
	0x65, 0x61, 0x64, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x72, 0x0a, 0x16,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x42, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x6c, 0x75, 0x65, 0x6e, 0x74,
	0x5f, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x66, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x66, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x42, 0x69, 0x74, 0x43, 0x66, 0x67, 0x12, 0x15, 0x0a, 0x06,
	0x73, 0x61, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x61,
	0x4b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x65, 0x6e, 0x76,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x45, 0x6e, 0x76,
	0x22, 0x19, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x75, 0x65, 0x6e, 0x74,
	0x42, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xcc, 0x01, 0x0a, 0x09,
	0x53, 0x65, 0x65, 0x73, 0x61, 0x77, 0x45, 0x43, 0x55, 0x12, 0x39, 0x0a, 0x08, 0x46, 0x61, 0x69,
	0x6c, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x65, 0x63, 0x75, 0x2e, 0x46, 0x61, 0x69, 0x6c,
	0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x65, 0x63,
	0x75, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x12, 0x14, 0x2e, 0x65, 0x63, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x65, 0x63, 0x75, 0x2e, 0x53, 0x65, 0x65,
	0x73, 0x61, 0x77, 0x53, 0x74, 0x61, 0x74, 0x73, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0f, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x42, 0x69, 0x74, 0x12, 0x1b, 0x2e,
	0x65, 0x63, 0x75, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x75, 0x65, 0x6e, 0x74,
	0x42, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x65, 0x63, 0x75,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x42, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x73, 0x65, 0x65, 0x73, 0x61, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x65, 0x63, 0x75, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ecu_proto_rawDescOnce sync.Once
	file_ecu_proto_rawDescData = file_ecu_proto_rawDesc
)

func file_ecu_proto_rawDescGZIP() []byte {
	file_ecu_proto_rawDescOnce.Do(func() {
		file_ecu_proto_rawDescData = protoimpl.X.CompressGZIP(file_ecu_proto_rawDescData)
	})
	return file_ecu_proto_rawDescData
}

var file_ecu_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ecu_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ecu_proto_goTypes = []interface{}{
	(SeesawStats_HAState)(0),        // 0: ecu.SeesawStats.HAState
	(*FailoverRequest)(nil),         // 1: ecu.FailoverRequest
	(*FailoverResponse)(nil),        // 2: ecu.FailoverResponse
	(*GetStatsRequest)(nil),         // 3: ecu.GetStatsRequest
	(*SeesawStats)(nil),             // 4: ecu.SeesawStats
	(*Readiness)(nil),               // 5: ecu.Readiness
	(*UpdateFluentBitRequest)(nil),  // 6: ecu.UpdateFluentBitRequest
	(*UpdateFluentBitResponse)(nil), // 7: ecu.UpdateFluentBitResponse
}
var file_ecu_proto_depIdxs = []int32{
	0, // 0: ecu.SeesawStats.ha_state:type_name -> ecu.SeesawStats.HAState
	5, // 1: ecu.SeesawStats.readiness:type_name -> ecu.Readiness
	1, // 2: ecu.SeesawECU.Failover:input_type -> ecu.FailoverRequest
	3, // 3: ecu.SeesawECU.GetStats:input_type -> ecu.GetStatsRequest
	6, // 4: ecu.SeesawECU.UpdateFluentBit:input_type -> ecu.UpdateFluentBitRequest
	2, // 5: ecu.SeesawECU.Failover:output_type -> ecu.FailoverResponse
	4, // 6: ecu.SeesawECU.GetStats:output_type -> ecu.SeesawStats
	7, // 7: ecu.SeesawECU.UpdateFluentBit:output_type -> ecu.UpdateFluentBitResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ecu_proto_init() }
func file_ecu_proto_init() {
	if File_ecu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ecu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FailoverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ecu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FailoverResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ecu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ecu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeesawStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ecu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Readiness); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ecu_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFluentBitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ecu_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFluentBitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ecu_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ecu_proto_goTypes,
		DependencyIndexes: file_ecu_proto_depIdxs,
		EnumInfos:         file_ecu_proto_enumTypes,
		MessageInfos:      file_ecu_proto_msgTypes,
	}.Build()
	File_ecu_proto = out.File
	file_ecu_proto_rawDesc = nil
	file_ecu_proto_goTypes = nil
	file_ecu_proto_depIdxs = nil
}
