// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/ecu/ecu.proto

package ecu

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// HAState reported by Seesaw. It's the protobuffer equivalent of Seesaw.HAState.
type SeesawStats_HAState int32

const (
	SeesawStats_HA_UNKNOWN  SeesawStats_HAState = 0
	SeesawStats_HA_BACKUP   SeesawStats_HAState = 1
	SeesawStats_HA_DISABLED SeesawStats_HAState = 2
	SeesawStats_HA_ERROR    SeesawStats_HAState = 3
	SeesawStats_HA_MASTER   SeesawStats_HAState = 4
	SeesawStats_HA_SHUTDOWN SeesawStats_HAState = 5
)

var SeesawStats_HAState_name = map[int32]string{
	0: "HA_UNKNOWN",
	1: "HA_BACKUP",
	2: "HA_DISABLED",
	3: "HA_ERROR",
	4: "HA_MASTER",
	5: "HA_SHUTDOWN",
}

var SeesawStats_HAState_value = map[string]int32{
	"HA_UNKNOWN":  0,
	"HA_BACKUP":   1,
	"HA_DISABLED": 2,
	"HA_ERROR":    3,
	"HA_MASTER":   4,
	"HA_SHUTDOWN": 5,
}

func (x SeesawStats_HAState) String() string {
	return proto.EnumName(SeesawStats_HAState_name, int32(x))
}

func (SeesawStats_HAState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9628f06b90eec907, []int{3, 0}
}

// Request for failover.
type FailoverRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailoverRequest) Reset()         { *m = FailoverRequest{} }
func (m *FailoverRequest) String() string { return proto.CompactTextString(m) }
func (*FailoverRequest) ProtoMessage()    {}
func (*FailoverRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9628f06b90eec907, []int{0}
}

func (m *FailoverRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailoverRequest.Unmarshal(m, b)
}
func (m *FailoverRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailoverRequest.Marshal(b, m, deterministic)
}
func (m *FailoverRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailoverRequest.Merge(m, src)
}
func (m *FailoverRequest) XXX_Size() int {
	return xxx_messageInfo_FailoverRequest.Size(m)
}
func (m *FailoverRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FailoverRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FailoverRequest proto.InternalMessageInfo

// Response for failover.
type FailoverResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailoverResponse) Reset()         { *m = FailoverResponse{} }
func (m *FailoverResponse) String() string { return proto.CompactTextString(m) }
func (*FailoverResponse) ProtoMessage()    {}
func (*FailoverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9628f06b90eec907, []int{1}
}

func (m *FailoverResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailoverResponse.Unmarshal(m, b)
}
func (m *FailoverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailoverResponse.Marshal(b, m, deterministic)
}
func (m *FailoverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailoverResponse.Merge(m, src)
}
func (m *FailoverResponse) XXX_Size() int {
	return xxx_messageInfo_FailoverResponse.Size(m)
}
func (m *FailoverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FailoverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FailoverResponse proto.InternalMessageInfo

type GetStatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatsRequest) Reset()         { *m = GetStatsRequest{} }
func (m *GetStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatsRequest) ProtoMessage()    {}
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9628f06b90eec907, []int{2}
}

func (m *GetStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatsRequest.Unmarshal(m, b)
}
func (m *GetStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatsRequest.Merge(m, src)
}
func (m *GetStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatsRequest.Size(m)
}
func (m *GetStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatsRequest proto.InternalMessageInfo

// SeesawStats includes stats that are interested by syllogi.
type SeesawStats struct {
	// Hostname of the instance.
	Hostname string              `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	HaState  SeesawStats_HAState `protobuf:"varint,2,opt,name=ha_state,json=haState,proto3,enum=ecu.SeesawStats_HAState" json:"ha_state,omitempty"`
	// If current instance is ready to serve traffic.
	Readiness            *Readiness `protobuf:"bytes,3,opt,name=readiness,proto3" json:"readiness,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SeesawStats) Reset()         { *m = SeesawStats{} }
func (m *SeesawStats) String() string { return proto.CompactTextString(m) }
func (*SeesawStats) ProtoMessage()    {}
func (*SeesawStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_9628f06b90eec907, []int{3}
}

func (m *SeesawStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeesawStats.Unmarshal(m, b)
}
func (m *SeesawStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeesawStats.Marshal(b, m, deterministic)
}
func (m *SeesawStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeesawStats.Merge(m, src)
}
func (m *SeesawStats) XXX_Size() int {
	return xxx_messageInfo_SeesawStats.Size(m)
}
func (m *SeesawStats) XXX_DiscardUnknown() {
	xxx_messageInfo_SeesawStats.DiscardUnknown(m)
}

var xxx_messageInfo_SeesawStats proto.InternalMessageInfo

func (m *SeesawStats) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *SeesawStats) GetHaState() SeesawStats_HAState {
	if m != nil {
		return m.HaState
	}
	return SeesawStats_HA_UNKNOWN
}

func (m *SeesawStats) GetReadiness() *Readiness {
	if m != nil {
		return m.Readiness
	}
	return nil
}

type Readiness struct {
	IsReady bool `protobuf:"varint,1,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	// A string message decribing why it's not ready.
	// Not filled if ready.
	// For logging and debugging purpose.
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Readiness) Reset()         { *m = Readiness{} }
func (m *Readiness) String() string { return proto.CompactTextString(m) }
func (*Readiness) ProtoMessage()    {}
func (*Readiness) Descriptor() ([]byte, []int) {
	return fileDescriptor_9628f06b90eec907, []int{4}
}

func (m *Readiness) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Readiness.Unmarshal(m, b)
}
func (m *Readiness) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Readiness.Marshal(b, m, deterministic)
}
func (m *Readiness) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Readiness.Merge(m, src)
}
func (m *Readiness) XXX_Size() int {
	return xxx_messageInfo_Readiness.Size(m)
}
func (m *Readiness) XXX_DiscardUnknown() {
	xxx_messageInfo_Readiness.DiscardUnknown(m)
}

var xxx_messageInfo_Readiness proto.InternalMessageInfo

func (m *Readiness) GetIsReady() bool {
	if m != nil {
		return m.IsReady
	}
	return false
}

func (m *Readiness) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterEnum("ecu.SeesawStats_HAState", SeesawStats_HAState_name, SeesawStats_HAState_value)
	proto.RegisterType((*FailoverRequest)(nil), "ecu.FailoverRequest")
	proto.RegisterType((*FailoverResponse)(nil), "ecu.FailoverResponse")
	proto.RegisterType((*GetStatsRequest)(nil), "ecu.GetStatsRequest")
	proto.RegisterType((*SeesawStats)(nil), "ecu.SeesawStats")
	proto.RegisterType((*Readiness)(nil), "ecu.Readiness")
}

func init() { proto.RegisterFile("pb/ecu/ecu.proto", fileDescriptor_9628f06b90eec907) }

var fileDescriptor_9628f06b90eec907 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0x41, 0x4f, 0xe2, 0x40,
	0x14, 0xa6, 0xb0, 0x0b, 0xed, 0x63, 0x17, 0x66, 0x27, 0xab, 0xa9, 0x9c, 0x48, 0x4f, 0x1c, 0x0c,
	0x26, 0xe0, 0xc5, 0x8b, 0xc9, 0x00, 0xd5, 0x1a, 0x14, 0xcc, 0x94, 0xc6, 0x63, 0x33, 0xe0, 0x8b,
	0x34, 0xd1, 0x16, 0x3b, 0x83, 0x86, 0xc4, 0xbf, 0xed, 0xdd, 0x74, 0x6c, 0xc1, 0xf4, 0x30, 0x99,
	0x79, 0xdf, 0x7c, 0xef, 0xe5, 0xfb, 0xde, 0x07, 0x64, 0xb3, 0x3c, 0xc3, 0xd5, 0x36, 0x3b, 0xfd,
	0x4d, 0x9a, 0xa8, 0x84, 0xd6, 0x70, 0xb5, 0x75, 0xfe, 0x41, 0xfb, 0x4a, 0x44, 0xcf, 0xc9, 0x1b,
	0xa6, 0x1c, 0x5f, 0xb7, 0x28, 0x95, 0x43, 0x81, 0x1c, 0x20, 0xb9, 0x49, 0x62, 0x89, 0x19, 0xed,
	0x1a, 0x95, 0xaf, 0x84, 0x92, 0x05, 0xed, 0xd3, 0x80, 0xa6, 0x8f, 0x28, 0xc5, 0xbb, 0x86, 0x69,
	0x07, 0xcc, 0x75, 0x22, 0x55, 0x2c, 0x5e, 0xd0, 0x36, 0xba, 0x46, 0xcf, 0xe2, 0xfb, 0x9a, 0x0e,
	0xc1, 0x5c, 0x8b, 0x50, 0x2a, 0xa1, 0xd0, 0xae, 0x76, 0x8d, 0x5e, 0x6b, 0x60, 0xf7, 0x33, 0x21,
	0x3f, 0xfa, 0xfb, 0x1e, 0xcb, 0x6e, 0xe4, 0x8d, 0xb5, 0xd0, 0x0f, 0x7a, 0x0a, 0x56, 0x8a, 0xe2,
	0x31, 0x8a, 0x51, 0x4a, 0xbb, 0xd6, 0x35, 0x7a, 0xcd, 0x41, 0x4b, 0x77, 0xf1, 0x02, 0xe5, 0x07,
	0x82, 0xf3, 0x04, 0x8d, 0x7c, 0x02, 0x6d, 0x01, 0x78, 0x2c, 0x0c, 0x66, 0xd3, 0xd9, 0xfc, 0x61,
	0x46, 0x2a, 0xf4, 0x2f, 0x58, 0x1e, 0x0b, 0x47, 0x6c, 0x3c, 0x0d, 0xee, 0x89, 0x41, 0xdb, 0xd0,
	0xf4, 0x58, 0x38, 0xb9, 0xf1, 0xd9, 0xe8, 0xd6, 0x9d, 0x90, 0x2a, 0xfd, 0x03, 0xa6, 0xc7, 0x42,
	0x97, 0xf3, 0x39, 0x27, 0xb5, 0x9c, 0x7d, 0xc7, 0xfc, 0x85, 0xcb, 0xc9, 0xaf, 0x9c, 0xed, 0x7b,
	0xc1, 0x62, 0x92, 0x4d, 0xfb, 0xed, 0x5c, 0x82, 0xb5, 0x17, 0x40, 0x4f, 0xc0, 0x8c, 0x64, 0x98,
	0xa9, 0xd8, 0x69, 0xd3, 0x26, 0x6f, 0x44, 0x32, 0xfb, 0xde, 0xd1, 0x63, 0xa8, 0xa7, 0x28, 0x64,
	0x12, 0x6b, 0xc7, 0x16, 0xcf, 0xab, 0xc1, 0x07, 0x58, 0xdf, 0xb6, 0xdd, 0x71, 0x40, 0x2f, 0xc0,
	0x2c, 0x76, 0x4d, 0xff, 0x6b, 0x73, 0xa5, 0x34, 0x3a, 0x47, 0x25, 0x34, 0x0f, 0xa4, 0x42, 0xcf,
	0xc1, 0x2c, 0x22, 0xc9, 0x5b, 0x4b, 0x09, 0x75, 0x48, 0x79, 0xc7, 0x4e, 0x65, 0x59, 0xd7, 0xd9,
	0x0f, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x24, 0x61, 0x17, 0x0f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SeesawECUClient is the client API for SeesawECU service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SeesawECUClient interface {
	// Calling Failover() on any of the LB instance triggers a switch of master.
	Failover(ctx context.Context, in *FailoverRequest, opts ...grpc.CallOption) (*FailoverResponse, error)
	// Returns SeesawStats.
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*SeesawStats, error)
}

type seesawECUClient struct {
	cc *grpc.ClientConn
}

func NewSeesawECUClient(cc *grpc.ClientConn) SeesawECUClient {
	return &seesawECUClient{cc}
}

func (c *seesawECUClient) Failover(ctx context.Context, in *FailoverRequest, opts ...grpc.CallOption) (*FailoverResponse, error) {
	out := new(FailoverResponse)
	err := c.cc.Invoke(ctx, "/ecu.SeesawECU/Failover", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seesawECUClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*SeesawStats, error) {
	out := new(SeesawStats)
	err := c.cc.Invoke(ctx, "/ecu.SeesawECU/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeesawECUServer is the server API for SeesawECU service.
type SeesawECUServer interface {
	// Calling Failover() on any of the LB instance triggers a switch of master.
	Failover(context.Context, *FailoverRequest) (*FailoverResponse, error)
	// Returns SeesawStats.
	GetStats(context.Context, *GetStatsRequest) (*SeesawStats, error)
}

// UnimplementedSeesawECUServer can be embedded to have forward compatible implementations.
type UnimplementedSeesawECUServer struct {
}

func (*UnimplementedSeesawECUServer) Failover(ctx context.Context, req *FailoverRequest) (*FailoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Failover not implemented")
}
func (*UnimplementedSeesawECUServer) GetStats(ctx context.Context, req *GetStatsRequest) (*SeesawStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}

func RegisterSeesawECUServer(s *grpc.Server, srv SeesawECUServer) {
	s.RegisterService(&_SeesawECU_serviceDesc, srv)
}

func _SeesawECU_Failover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeesawECUServer).Failover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ecu.SeesawECU/Failover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeesawECUServer).Failover(ctx, req.(*FailoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeesawECU_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeesawECUServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ecu.SeesawECU/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeesawECUServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SeesawECU_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ecu.SeesawECU",
	HandlerType: (*SeesawECUServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Failover",
			Handler:    _SeesawECU_Failover_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _SeesawECU_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/ecu/ecu.proto",
}
